language: python
python:
  - "3.6"

services:
  - mysql

before_install:
  - mysql -u root --password="" < Service/db/init.sql

install:
  - pip install -r requirements.txt
  - cd Web/stockdogweb && npm install && cd ../..

before_script:
  - cd Service/src/ && python3 app.py --environment travis &
  - sleep 10

script:
  - cd tests/ && python3 Runner.py

notifications:
   slack: stockdog-app:Q4crKXH7YschvHLyBoOVytQS
